let tunesInfo = [
    /*
    {
        "data": "url",
        "score": "譜面のデータ(形は考え中)",
        "name":"曲名",
        "time": "時間(ms)",
        "BPM":"BPM",
        "description":"説明",
        "scoreRate":{
            "C":"Cランクのスコア",
            "B":"B同上",
            "A":"A同上",
            "AA":"AA同上",
            "S":"S同上",
            }
    }
    */
    {
        "data": "sss",
        "score": {
            0: s0n,
            1: s0h
        },
        "name": "シャイニングスター",
        "font": "Kaisei Opti",
        "time": 94000,
        "BPM": 158,
        "credit": "作詞作曲：森田交一 ボーカル：詩歩 ベース＆ギター：森田交一",
        "scoreRate": {
            "D": "Dランクのスコア",
            "C": "Cランクのスコア",
            "B": "B同上",
            "A": "A同上",
            "AA": "AA同上",
            "S": "S同上",
        },
        "highScore": {
            "normal": 0,
            "hard": 0,
        },
    },
    {
        "data": "./tune/まだ",
        "score": "譜面のデータ(形は考え中)",
        "name": "君が代",
        "font": "Yuji Mai",
        "time": 6000,
        "BPM": 100,
        "credit": "日本国国家",
        "scoreRate": {
            "D": "Dランクのスコア",
            "C": "Cランクのスコア",
            "B": "B同上",
            "A": "A同上",
            "AA": "AA同上",
            "S": "S同上",
        },
        "highScore": {
            "normal": 0,
            "hard": 0,
        },
    },
    {
        "data": "./tune/まだ",
        "score": "譜面のデータ(形は考え中)",
        "name": "おおきなふるどけい",
        "font": "Shippori Antique",
        "time": 6000,
        "BPM": 100,
        "credit": "たろう16bitさんのやつ好き",
        "scoreRate": {
            "D": "Dランクのスコア",
            "C": "Cランクのスコア",
            "B": "B同上",
            "A": "A同上",
            "AA": "AA同上",
            "S": "S同上",
        },
        "highScore": {
            "normal": 0,
            "hard": 0,
        },
    },
    {
        "data": "./tune/まだ",
        "score": "譜面のデータ(形は考え中)",
        "name": "アルプス一万尺",
        "font": "Yuji Boku",
        "time": 6000,
        "BPM": 100,
        "credit": "民謡・童謡",
        "scoreRate": {
            "D": "Dランクのスコア",
            "C": "Cランクのスコア",
            "B": "B同上",
            "A": "A同上",
            "AA": "AA同上",
            "S": "S同上",
        },
        "highScore": {
            "normal": 0,
            "hard": 0,
        },
    },
    {
        "data": "./tune/まだ",
        "score": "譜面のデータ(形は考え中)",
        "name": "カノン",
        "font": "Reggae One",
        "time": 6000,
        "BPM": 100,
        "credit": "作曲：パッヘルベル",
        "scoreRate": {
            "D": "Dランクのスコア",
            "C": "Cランクのスコア",
            "B": "B同上",
            "A": "A同上",
            "AA": "AA同上",
            "S": "S同上",
        },
        "highScore": {
            "normal": 0,
            "hard": 0,
        },
    },
    {
        "data": "./tune/まだ",
        "score": "譜面のデータ(形は考え中)",
        "name": "春日部共栄中学高等学校校歌",
        "font": "Yuji Syuku",
        "time": 6000,
        "BPM": 100,
        "credit": "春日部共栄我が母校",
        "scoreRate": {
            "D": "Dランクのスコア",
            "C": "Cランクのスコア",
            "B": "B同上",
            "A": "A同上",
            "AA": "AA同上",
            "S": "S同上",
        },
        "highScore": {
            "normal": 0,
            "hard": 0,
        },
    },
    {
        "data": "./tune/まだ",
        "score": "譜面のデータ(形は考え中)",
        "name": "キラキラ星",
        "font": "Kaisei Decol",
        "time": 6000,
        "BPM": 100,
        "credit": "特になし",
        "scoreRate": {
            "D": "Dランクのスコア",
            "C": "Cランクのスコア",
            "B": "B同上",
            "A": "A同上",
            "AA": "AA同上",
            "S": "S同上",
        },
        "highScore": {
            "normal": 0,
            "hard": 0,
        },
    },
    {
        "data": "./tune/まだ",
        "score": "譜面のデータ(形は考え中)",
        "name": "エリーゼのために",
        "font": "Rampart One",
        "time": 6000,
        "BPM": 100,
        "credit": "作曲：ベートーベン",
        "scoreRate": {
            "D": "Dランクのスコア",
            "C": "Cランクのスコア",
            "B": "B同上",
            "A": "A同上",
            "AA": "AA同上",
            "S": "S同上",
        },
        "highScore": {
            "normal": 0,
            "hard": 0,
        },
    },
];